=== OI4/oi4-oec-service/packages/oi4-oec-json-schemas/src/schemas/DataSetMetaData.schema.json
{
  "$id": "DataSetMetaData.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of a metadata message",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "DataSetWriterId",
    "WriterGroupName",
    "MessageId",
    "MessageType",
    "PublisherId",
    "MetaData",
    "DataSetWriterName"
  ],
  "properties": {
    "ReplyTo": {
      "type": "string",
      "description": "ReplyTo ID used for logging and as debug information"
    },
    "DataSetWriterId": {
      "$ref": "dataTypes/uint16.schema.json"
    },
    "WriterGroupName": {
      "type": "string",
      "description": "In combination with the used Resource in the topic, the WriterGroupName, together with the DataSetWriterName, contains the readable reference to the DataSetWriterId and is identical to the WriterGroupName in the topic (8.1.7)."
    },
    "MessageId": {
      "type": "string",
      "description": "Message ID",
      "pattern": "^.{1,}-(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "MetaData": {
      "$ref": "DataSetMetaDataType.schema.json"
    },
    "MessageType": {
      "const": "ua-metadata",
      "description": "Message Type"
    },
    "PublisherId": {
      "type": "string",
      "description": "Publisher ID",
      "pattern:": "^.+/[a-z0-9-.]+/.+/.+/.+$",
      "pattern": "^(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "DataSetWriterName": {
      "type": "string",
      "description": "In combination with the used Resource in the topic, the DataSetWriterName, together with the WriterGroupName, contains the readable reference to the DataSetWriterId and is identical to the DataSetWriterName in the topic (8.1.6) if present."
    }
  }
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/metadata_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-metadata",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetWriterId": 753,
  "WriterGroupName": "oee",
  "DataSetWriterName": "openindustry4.com/nd/nd/nd",
  "ReplyTo": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "MetaData": {
    "Name": "Dataset1",
    "Description": {
      "Text": "Description",
      "Locale": "en-US"
    },
    "Namespaces": [],
    "StructureDataTypes": [],
    "EnumDataTypes": [],
    "SimpleDataTypes": []
  }
}
