=== OI4/oi4-oec-service/packages/oi4-oec-json-schemas/src/schemas/NetworkMessage.schema.json
{
  "$id": "NetworkMessage.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "OPC UA PubSub NetworkMessage representation",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "MessageId",
    "MessageType",
    "PublisherId",
    "Messages"
  ],
  "properties": {
    "ReplyTo": {
      "type": "string",
      "description": "Optional correlation identifier for request-response matching. Used to correlate response messages to their original request. Follows OPC UA Part 14-7.2.2.1 specification."
    },
    "DataSetClassId": {
      "type": "string",
      "description": "Dataset Class ID",
      "pattern": "^[0-9a-fA-F-]+$"
    },
    "MessageId": {
      "type": "string",
      "description": "Message ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^.{1,}-(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "MessageType": {
      "const": "ua-data",
      "description": "Message Type"
    },
    "PublisherId": {
      "type": "string",
      "description": "Publisher ID",
      "$comment": "TODO: find a way to include the oi4Identifier better here",
      "pattern": "^(Registry|OTConnector|Utility|Persistence|Aggregation|OOCConnector|ITConnector)\\/(([a-z0-9-]+\\.)*([a-z0-9-]*)(?:\\/[^\\/`\\^\r\n]+){3})$"
    },
    "Messages": {
      "type": "array",
      "description": "Messages Array",
      "items": {
        "$ref": "DataSetMessage.schema.json"
      }
    }
  }
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/profile_device_data_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "48017c6a-05c8-48d7-9d85-4b08bbb707f3",
  "ReplyTo": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 74,
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 42,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Resources": [
          "MAM",
          "Health",
          "Profile",
          "ReferenceDesignation",
		      "Data",
		      "Metadata"
        ]
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/health_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "d8e7b6df-42ba-448a-975a-199f59e8ffeb",
  "ReplyTo": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 3456,
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 57,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Health": "NORMAL_0",
        "HealthScore": 100
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/data_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "ReplyTo": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 93,
      "WriterGroupName": "oee",
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 3985,
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "availability": 90,
        "performanceRate": 95,
        "qualityRate": 98,
        "product": 84
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/event_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "543ae05e-b6d9-4161-a0a3-350a0fac5976",
  "ReplyTo": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [
    {
      "DataSetWriterId": 623,
      "WriterGroupName": "Status/Good",
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 14,
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "Number": 0,
        "Description": "The operation succeeded.",
        "Category": "CAT_STATUS_1",
        "Details": {
          "SymbolicId": "Good"
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-model/test/__fixtures__/mam_network_message.json
{
  "MessageId": "1639693510094-OTConnector/provider.com/FieldDataService/FDS-001/1200-0345",
  "MessageType": "ua-data",
  "PublisherId": "OTConnector/provider.com/FieldDataService/FDS-001/1200-0345",
  "DataSetClassId": "360ca8f3-5e66-42a2-8f10-9cdf45f4bf58",
  "ReplyTo": "1639693510000-ITConnector/consumer.com/MEService/MES%2fOnPrem/Inst07322",
  "Messages": [
    {
      "DataSetWriterId": 1,
      "DataSetWriterName": "provider.com/FieldDataService/FDS-001/1200-0345",
      "SequenceNumber": 4,
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "Manufacturer": {
          "Locale": "en-US",
          "Text": "Provider Ltd."
        },
        "ManufacturerUri": "provider.com",
        "Model": {
          "Locale": "en-US",
          "Text": "FieldDataService"
        },
        "ProductCode": "FDS-001",
        "HardwareRevision": "",
        "SoftwareRevision": "1.0.1",
        "DeviceRevision": "",
        "DeviceManual": "https://provider.com/manuals/FDS-001.pdf",
        "DeviceClass": "OI4.OTConnector",
        "SerialNumber": "1200-0345",
        "ProductInstanceUri": "provider.com/FieldDataService/FDS-001/1200-0345",
        "RevisionCounter": 1,
        "Description": {
          "Locale": "en-US",
          "Text": "This OT connector provides field data"
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/config_valid.json
{
  "MessageId": "1639693510094-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "9d5983db-440d-4474-9fd7-1cd7a6c8b6c2",
  "ReplyTo": "1639693510000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [
    {
      "DataSetWriterId": 42,
      "WriterGroupName": "Network%20settings",
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "Timestamp": "2021-12-16T22:25:10.094Z",
      "Payload": {
        "network": {
          "Name": {
            "Locale": "en-US",
            "Text": "Network"
          },
          "Description": {
            "Locale": "en-US",
            "Text": "Describes the network configuration of this service"
          },
          "ip_address": {
            "Description": {
              "Locale": "en-US",
              "Text": "IP address of Network DNS server"
            },
            "Name": {
              "Locale": "en-US",
              "Text": "IP Address"
            },
            "Type": "String",
            "Validation": {
              "Pattern": "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
            },
            "Value": ""
          },
          "subnet-mask": {
            "Description": {
              "Locale": "en-US",
              "Text": "Subnetmask of Network"
            },
            "Name": {
              "Locale": "en-US",
              "Text": "Subnetmask"
            },
            "Type": "String",
            "Validation": {
              "Pattern": "^(((255\\.){3}(255|254|252|248|240|224|192|128|0+))|((255\\.){2}(255|254|252|248|240|224|192|128|0+)\\.0)|((255\\.)(255|254|252|248|240|224|192|128|0+)(\\.0+){2})|((255|254|252|248|240|224|192|128|0+)(\\.0+){3}))$"
            },
            "Value": ""
          },
          "port": {
            "DefaultValue": "80",
            "Mandatory": false,
            "Name": {
              "Locale": "en-US",
              "Text": "Port"
            },
            "Type": "Number",
            "Validation": {
              "Min": 0,
              "Max": 65535
            },
            "Value": ""
          }
        },
        "Context": {
          "Name": {
            "Locale": "en-US",
            "Text": "Network settings"
          },
          "Description": {
            "Locale": "en-US",
            "Text": "Settings of all network interfaces"
          }
        }
      }
    }
  ]
}

=== OI4/oi4-oec-service/packages/oi4-oec-service-conformity-validator/tests/__fixtures__/referenceDesignation_valid.json
{
  "MessageId": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "MessageType": "ua-data",
  "PublisherId": "Registry/openindustry4.com/nd/nd/nd",
  "DataSetClassId": "27a75019-164a-496d-a38b-90e8a55c2cfa",
  "ReplyTo": "1577836800000-Registry/openindustry4.com/nd/nd/nd",
  "Messages": [{
      "DataSetWriterId": 489,
      "WriterGroupName": "room_206",
      "DataSetWriterName": "openindustry4.com/nd/nd/nd",
      "SequenceNumber": 17,
      "Timestamp": "2020-01-01T00:00:00.000Z",
      "Payload": {
        "Location": {
          "Value": "room_206",
          "Local": "Room 206",
          "Parent": {
            "Value": "floor_2",
            "Local": "Floor 2",
            "Oi4Identifier": "provider.com/FieldDataService/FDS-001/1200-0345"
          }
        }
      }
    }
  ]
}
